# Generated by Django 5.2.5 on 2025-09-12 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("new_registrations", models.IntegerField(default=0)),
                ("total_appointments", models.IntegerField(default=0)),
                ("completed_appointments", models.IntegerField(default=0)),
                ("cancelled_appointments", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Metric",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SystemPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("cpu_usage", models.FloatField(help_text="CPU usage percentage")),
                (
                    "memory_usage",
                    models.FloatField(help_text="Memory usage percentage"),
                ),
                ("disk_usage", models.FloatField(help_text="Disk usage percentage")),
                ("active_sessions", models.IntegerField(default=0)),
                (
                    "api_response_time",
                    models.FloatField(help_text="Average API response time in ms"),
                ),
                ("database_queries", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("uptime_hours", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "System Performance",
                "verbose_name_plural": "System Performance",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("dermatology", "Dermatology"),
                            ("neurology", "Neurology"),
                            ("orthopedics", "Orthopedics"),
                            ("pediatrics", "Pediatrics"),
                            ("general", "General Medicine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("total_appointments", models.IntegerField(default=0)),
                ("completed_appointments", models.IntegerField(default=0)),
                ("no_show_appointments", models.IntegerField(default=0)),
                ("cancelled_appointments", models.IntegerField(default=0)),
                ("average_duration", models.DurationField(blank=True, null=True)),
                ("peak_hour", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Appointment Analytics",
                "verbose_name_plural": "Appointment Analytics",
                "ordering": ["-date", "department"],
                "unique_together": {("date", "department")},
            },
        ),
        migrations.CreateModel(
            name="PatientDemographics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("0-18", "0-18 years"),
                            ("19-35", "19-35 years"),
                            ("36-50", "36-50 years"),
                            ("51-65", "51-65 years"),
                            ("65+", "65+ years"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("total_patients", models.IntegerField(default=0)),
                ("new_patients", models.IntegerField(default=0)),
                ("returning_patients", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Patient Demographics",
                "verbose_name_plural": "Patient Demographics",
                "ordering": ["-date", "age_group", "gender"],
                "unique_together": {("date", "age_group", "gender")},
            },
        ),
        migrations.CreateModel(
            name="PopularServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("service_name", models.CharField(max_length=200)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("dermatology", "Dermatology"),
                            ("neurology", "Neurology"),
                            ("orthopedics", "Orthopedics"),
                            ("pediatrics", "Pediatrics"),
                            ("general", "General Medicine"),
                        ],
                        max_length=50,
                    ),
                ),
                ("booking_count", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of completed appointments"
                    ),
                ),
                ("average_rating", models.FloatField(blank=True, null=True)),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Popular Service",
                "verbose_name_plural": "Popular Services",
                "ordering": ["-date", "-booking_count"],
                "unique_together": {("date", "service_name", "department")},
            },
        ),
        migrations.CreateModel(
            name="RevenueAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("dermatology", "Dermatology"),
                            ("neurology", "Neurology"),
                            ("orthopedics", "Orthopedics"),
                            ("pediatrics", "Pediatrics"),
                            ("general", "General Medicine"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "consultation_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "procedure_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "prescription_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "outstanding_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method_card",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method_insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Revenue Analytics",
                "verbose_name_plural": "Revenue Analytics",
                "ordering": ["-date", "department"],
                "unique_together": {("date", "department")},
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("login_count", models.IntegerField(default=0)),
                ("appointments_booked", models.IntegerField(default=0)),
                ("appointments_attended", models.IntegerField(default=0)),
                ("prescriptions_filled", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-date", "user"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
