# Generated by Django 5.2.5 on 2025-09-12 14:50

import authentication.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnhancedPatient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("separated", "Separated"),
                            ("domestic_partner", "Domestic Partner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", authentication.models.EncryptedCharField(max_length=20)),
                (
                    "address_line1",
                    authentication.models.EncryptedCharField(max_length=255),
                ),
                (
                    "address_line2",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                ("city", authentication.models.EncryptedCharField(max_length=100)),
                ("state", authentication.models.EncryptedCharField(max_length=50)),
                ("zip_code", authentication.models.EncryptedCharField(max_length=10)),
                ("country", models.CharField(default="United States", max_length=50)),
                (
                    "emergency_contact_name",
                    authentication.models.EncryptedCharField(max_length=255),
                ),
                (
                    "emergency_contact_relationship",
                    authentication.models.EncryptedCharField(max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    authentication.models.EncryptedCharField(max_length=20),
                ),
                (
                    "emergency_contact_email",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=10,
                    ),
                ),
                (
                    "height_inches",
                    models.PositiveIntegerField(
                        blank=True, help_text="Height in inches", null=True
                    ),
                ),
                (
                    "weight_lbs",
                    models.PositiveIntegerField(
                        blank=True, help_text="Weight in pounds", null=True
                    ),
                ),
                (
                    "allergies",
                    authentication.models.EncryptedTextField(
                        blank=True, help_text="Known allergies and reactions"
                    ),
                ),
                (
                    "current_medications",
                    authentication.models.EncryptedTextField(
                        blank=True, help_text="Current medications and dosages"
                    ),
                ),
                (
                    "medical_conditions",
                    authentication.models.EncryptedTextField(
                        blank=True, help_text="Chronic conditions and diagnoses"
                    ),
                ),
                (
                    "surgical_history",
                    authentication.models.EncryptedTextField(
                        blank=True, help_text="Previous surgeries and procedures"
                    ),
                ),
                (
                    "family_medical_history",
                    authentication.models.EncryptedTextField(
                        blank=True, help_text="Relevant family medical history"
                    ),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("former", "Former"),
                            ("current", "Current"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                (
                    "alcohol_use",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("occasional", "Occasional"),
                            ("moderate", "Moderate"),
                            ("heavy", "Heavy"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "exercise_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("rare", "Rarely"),
                            ("weekly", "1-2 times per week"),
                            ("regular", "3-4 times per week"),
                            ("daily", "Daily"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "insurance_provider",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("private", "Private Insurance"),
                            ("medicare", "Medicare"),
                            ("medicaid", "Medicaid"),
                            ("self_pay", "Self Pay"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "insurance_policy_number",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=100
                    ),
                ),
                (
                    "insurance_group_number",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=100
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(default="English", max_length=50),
                ),
                (
                    "preferred_communication",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("portal", "Patient Portal"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("hipaa_authorization_signed", models.BooleanField(default=False)),
                (
                    "hipaa_authorization_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("marketing_consent", models.BooleanField(default=False)),
                ("research_consent", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("registration_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enhanced_patients",
            },
        ),
        migrations.CreateModel(
            name="EnhancedStaffProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                (
                    "license_number",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=100
                    ),
                ),
                ("license_state", models.CharField(blank=True, max_length=50)),
                ("license_expiration", models.DateField(blank=True, null=True)),
                (
                    "license_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending Renewal"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "board_certifications",
                    authentication.models.EncryptedJSONField(
                        default=list,
                        help_text="List of board certifications with expiration dates",
                    ),
                ),
                (
                    "dea_number",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                ("dea_expiration", models.DateField(blank=True, null=True)),
                (
                    "npi_number",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("per_diem", "Per Diem"),
                            ("locum_tenens", "Locum Tenens"),
                            ("inactive", "Inactive"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "work_phone",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                ("work_email", models.EmailField(blank=True, max_length=254)),
                (
                    "pager",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                ("office_location", models.CharField(blank=True, max_length=255)),
                (
                    "office_address",
                    authentication.models.EncryptedTextField(blank=True),
                ),
                (
                    "default_schedule",
                    authentication.models.EncryptedJSONField(
                        default=dict, help_text="Default weekly schedule"
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "education",
                    authentication.models.EncryptedTextField(
                        blank=True, help_text="Educational background"
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        default=list, help_text="Languages spoken by the staff member"
                    ),
                ),
                (
                    "hospital_privileges",
                    authentication.models.EncryptedJSONField(
                        default=list,
                        help_text="Hospital privileges and admitting rights",
                    ),
                ),
                (
                    "emergency_contact_name",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=100
                    ),
                ),
                (
                    "emergency_contact_phone",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "professional_references",
                    authentication.models.EncryptedJSONField(
                        default=list,
                        help_text="Professional references with contact information",
                    ),
                ),
                ("background_check_date", models.DateField(blank=True, null=True)),
                (
                    "background_check_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared"),
                            ("flagged", "Flagged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hipaa_training_date", models.DateField(blank=True, null=True)),
                ("cpr_certification_date", models.DateField(blank=True, null=True)),
                ("cpr_expiration_date", models.DateField(blank=True, null=True)),
                ("last_performance_review", models.DateField(blank=True, null=True)),
                ("next_performance_review", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_prescribe", models.BooleanField(default=False)),
                ("can_order_tests", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "enhanced_staff_profiles",
            },
        ),
        migrations.CreateModel(
            name="PatientCareTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("primary_care", "Primary Care Physician"),
                            ("specialist", "Specialist"),
                            ("consulting", "Consulting Physician"),
                            ("nurse", "Primary Nurse"),
                            ("therapist", "Therapist"),
                            ("case_manager", "Case Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("assignment_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "patient_care_teams",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "specializations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StaffCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("license", "Professional License"),
                            ("certification", "Board Certification"),
                            ("training", "Training Certificate"),
                            ("cme", "Continuing Medical Education"),
                            ("other", "Other Credential"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credential_name", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(max_length=255)),
                (
                    "credential_number",
                    authentication.models.EncryptedCharField(
                        blank=True, max_length=100
                    ),
                ),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_credentials",
            },
        ),
    ]
