# Generated by Django 5.2.5 on 2025-09-23 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancedpatient",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enhancedpatient",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enhancedstaffprofile",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_staff_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enhancedstaffprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enhancedpatient",
            name="primary_care_physician",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "user__role__in": ["physician", "nurse_practitioner"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_patients",
                to="accounts.enhancedstaffprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["name"], name="hospitals_name_9e93ed_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["slug"], name="hospitals_slug_26fb1e_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["status"], name="hospitals_status_d2d127_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["hospital_type"], name="hospitals_hospita_2fee4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["created_at"], name="hospitals_created_a4fe78_idx"
            ),
        ),
        migrations.AddField(
            model_name="enhancedstaffprofile",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="accounts.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospitalpatient",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who added this patient to the hospital",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_hospital_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hospitalpatient",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_patients",
                to="accounts.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospitalpatient",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_relationships",
                to="accounts.enhancedpatient",
            ),
        ),
        migrations.AddField(
            model_name="patientcareteam",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="care_team_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientcareteam",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_team",
                to="accounts.enhancedpatient",
            ),
        ),
        migrations.AddField(
            model_name="patientcareteam",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_assignments",
                to="accounts.enhancedstaffprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="specialization",
            index=models.Index(fields=["name"], name="specializat_name_560ae9_idx"),
        ),
        migrations.AddIndex(
            model_name="specialization",
            index=models.Index(
                fields=["category"], name="specializat_categor_df1e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specialization",
            index=models.Index(
                fields=["is_active"], name="specializat_is_acti_694c60_idx"
            ),
        ),
        migrations.AddField(
            model_name="enhancedstaffprofile",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="accounts.specialization",
            ),
        ),
        migrations.AddField(
            model_name="staffcredential",
            name="staff_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="accounts.enhancedstaffprofile",
            ),
        ),
        migrations.AddField(
            model_name="staffcredential",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedpatient",
            index=models.Index(fields=["user"], name="enhanced_pa_user_id_89ddfc_idx"),
        ),
        migrations.AddIndex(
            model_name="enhancedpatient",
            index=models.Index(
                fields=["date_of_birth"], name="enhanced_pa_date_of_850173_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedpatient",
            index=models.Index(
                fields=["primary_care_physician"], name="enhanced_pa_primary_bea679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedpatient",
            index=models.Index(
                fields=["is_active"], name="enhanced_pa_is_acti_94cc32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedpatient",
            index=models.Index(
                fields=["created_at"], name="enhanced_pa_created_30acc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalpatient",
            index=models.Index(
                fields=["hospital", "status"], name="hospital_pa_hospita_d40f7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalpatient",
            index=models.Index(
                fields=["patient", "status"], name="hospital_pa_patient_451013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalpatient",
            index=models.Index(
                fields=["relationship_type"], name="hospital_pa_relatio_65844b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalpatient",
            index=models.Index(
                fields=["first_visit_date"], name="hospital_pa_first_v_195b70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalpatient",
            index=models.Index(
                fields=["last_visit_date"], name="hospital_pa_last_vi_caf336_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalpatient",
            index=models.Index(
                fields=["created_at"], name="hospital_pa_created_717190_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hospitalpatient",
            unique_together={("hospital", "patient")},
        ),
        migrations.AddIndex(
            model_name="patientcareteam",
            index=models.Index(
                fields=["patient", "is_active"], name="patient_car_patient_9af875_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientcareteam",
            index=models.Index(
                fields=["staff_member", "is_active"],
                name="patient_car_staff_m_af7dad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientcareteam",
            index=models.Index(
                fields=["relationship_type"], name="patient_car_relatio_b823f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientcareteam",
            unique_together={("patient", "staff_member", "relationship_type")},
        ),
        migrations.AddIndex(
            model_name="enhancedstaffprofile",
            index=models.Index(fields=["user"], name="enhanced_st_user_id_9ad76e_idx"),
        ),
        migrations.AddIndex(
            model_name="enhancedstaffprofile",
            index=models.Index(
                fields=["specialization"], name="enhanced_st_special_991efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedstaffprofile",
            index=models.Index(
                fields=["department"], name="enhanced_st_departm_d35e33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedstaffprofile",
            index=models.Index(
                fields=["employment_status"], name="enhanced_st_employm_acc0bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedstaffprofile",
            index=models.Index(
                fields=["license_expiration"], name="enhanced_st_license_1b2d9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enhancedstaffprofile",
            index=models.Index(
                fields=["is_active"], name="enhanced_st_is_acti_401093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcredential",
            index=models.Index(
                fields=["staff_profile"], name="staff_crede_staff_p_3a78e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcredential",
            index=models.Index(
                fields=["credential_type"], name="staff_crede_credent_c72812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcredential",
            index=models.Index(
                fields=["expiration_date"], name="staff_crede_expirat_363fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffcredential",
            index=models.Index(fields=["status"], name="staff_crede_status_ae68f6_idx"),
        ),
    ]
