# Generated by Django 5.2.5 on 2025-09-16 22:12

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedpatient",
            name="city",
            field=authentication.models.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="emergency_contact_phone",
            field=authentication.models.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="emergency_contact_relationship",
            field=authentication.models.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="phone",
            field=authentication.models.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="state",
            field=authentication.models.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="zip_code",
            field=authentication.models.EncryptedCharField(max_length=255),
        ),
    ]
