# Generated by Django 5.2.5 on 2025-12-31 16:43

import encryption.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancedpatient",
            name="national_id",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="address_line1",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="address_line2",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="allergies",
            field=encryption.fields.EnhancedEncryptedTextField(
                blank=True, help_text="Known allergies and reactions"
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="city",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="current_medications",
            field=encryption.fields.EnhancedEncryptedTextField(
                blank=True, help_text="Current medications and dosages"
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="emergency_contact_email",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="emergency_contact_name",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="emergency_contact_phone",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="emergency_contact_relationship",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="family_medical_history",
            field=encryption.fields.EnhancedEncryptedTextField(
                blank=True, help_text="Relevant family medical history"
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="insurance_group_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="insurance_policy_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="insurance_provider",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="medical_conditions",
            field=encryption.fields.EnhancedEncryptedTextField(
                blank=True, help_text="Chronic conditions and diagnoses"
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="phone",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="state",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="surgical_history",
            field=encryption.fields.EnhancedEncryptedTextField(
                blank=True, help_text="Previous surgeries and procedures"
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="zip_code",
            field=encryption.fields.EnhancedEncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="dea_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="education",
            field=encryption.fields.EnhancedEncryptedTextField(
                blank=True, help_text="Educational background"
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="emergency_contact_name",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="emergency_contact_phone",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="emergency_contact_relationship",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="license_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="npi_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="office_address",
            field=encryption.fields.EnhancedEncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="pager",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="work_phone",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="license_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="tax_id",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="staffcredential",
            name="credential_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=100
            ),
        ),
    ]
