# Generated by Django 5.2.5 on 2025-12-31 19:26

import encryption.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_enhancedpatient_national_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedpatient",
            name="insurance_group_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="enhancedpatient",
            name="insurance_policy_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="emergency_contact_relationship",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="enhancedstaffprofile",
            name="license_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="staffcredential",
            name="credential_number",
            field=encryption.fields.EnhancedEncryptedCharField(
                blank=True, max_length=500
            ),
        ),
    ]
