# Generated by Django 5.2.5 on 2026-01-01 10:11

import django.core.validators
import django.db.models.deletion
import encryption.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_enhancedpatient_insurance_group_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", encryption.fields.EnhancedEncryptedCharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("relative", "Other Relative"),
                            ("friend", "Friend"),
                            ("neighbor", "Neighbor"),
                            ("colleague", "Colleague"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", encryption.fields.EnhancedEncryptedCharField(max_length=255)),
                (
                    "email",
                    encryption.fields.EnhancedEncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "notify_appointments",
                    models.BooleanField(
                        default=True, help_text="Notify about appointment reminders"
                    ),
                ),
                (
                    "notify_cancellations",
                    models.BooleanField(
                        default=True, help_text="Notify about appointment cancellations"
                    ),
                ),
                (
                    "notify_reschedules",
                    models.BooleanField(
                        default=True, help_text="Notify about appointment reschedules"
                    ),
                ),
                (
                    "notify_emergencies",
                    models.BooleanField(
                        default=True, help_text="Notify about medical emergencies"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        help_text="Contact priority (2=secondary, 3=tertiary)",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_emergency_contacts",
                        to="accounts.enhancedpatient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "db_table": "emergency_contacts",
                "ordering": ["patient", "priority"],
                "indexes": [
                    models.Index(
                        fields=["patient", "is_active"],
                        name="emergency_c_patient_49591b_idx",
                    ),
                    models.Index(
                        fields=["patient", "priority"],
                        name="emergency_c_patient_4f6e3e_idx",
                    ),
                    models.Index(fields=["email"], name="emergency_c_email_143777_idx"),
                    models.Index(
                        fields=["created_at"], name="emergency_c_created_bfe26e_idx"
                    ),
                ],
                "unique_together": {("patient", "priority")},
            },
        ),
    ]
