# Generated by Django 5.2.5 on 2026-01-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_emergencycontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("medical_center", "Medical Center"),
                    ("urgent_care", "Urgent Care"),
                    ("specialty_clinic", "Specialty Clinic"),
                    ("dental_clinic", "Dental Clinic"),
                    ("veterinary_clinic", "Veterinary Clinic"),
                    ("general_hospital", "General Hospital"),
                    ("emergency_center", "Emergency Center"),
                    ("rehabilitation_center", "Rehabilitation Center"),
                    ("mental_health_facility", "Mental Health Facility"),
                    ("maternity_hospital", "Maternity Hospital"),
                    ("pediatric_hospital", "Pediatric Hospital"),
                    ("surgical_center", "Surgical Center"),
                    ("diagnostic_center", "Diagnostic Center"),
                ],
                default="clinic",
                max_length=50,
            ),
        ),
    ]
