# Generated by Django 4.2.23 on 2025-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
