# Generated by Django 5.2.5 on 2025-09-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_user_account_locked_until_user_failed_login_attempts_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
