# Generated by Django 5.2.5 on 2025-09-12 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Actual duration in minutes"),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(help_text="Reason for appointment")),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.JSONField(
                        blank=True,
                        help_text="Recurrence pattern (frequency, end date, etc.)",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("refunded", "Refunded"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointments",
            },
        ),
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "default_duration",
                    models.PositiveIntegerField(
                        help_text="Default duration in minutes"
                    ),
                ),
                (
                    "buffer_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time after appointment in minutes"
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base cost for this appointment type",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("requires_preparation", models.BooleanField(default=False)),
                ("preparation_instructions", models.TextField(blank=True)),
                ("requires_fasting", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color_code",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for calendar display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointment_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentWaitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preferred_date_start", models.DateField()),
                ("preferred_date_end", models.DateField()),
                ("preferred_time_start", models.TimeField(blank=True, null=True)),
                ("preferred_time_end", models.TimeField(blank=True, null=True)),
                (
                    "preferred_days",
                    models.JSONField(
                        default=list,
                        help_text="Preferred days of week (0=Monday, 6=Sunday)",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("notified", "Notified"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("response_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointment_waitlist",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("equipment_id", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("maintenance", "Under Maintenance"),
                            ("out_of_order", "Out of Order"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_portable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room_number", models.CharField(max_length=20, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation Room"),
                            ("examination", "Examination Room"),
                            ("procedure", "Procedure Room"),
                            ("surgery", "Surgery Room"),
                            ("lab", "Laboratory"),
                            ("imaging", "Imaging Room"),
                            ("therapy", "Therapy Room"),
                            ("conference", "Conference Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="Room features and equipment"
                    ),
                ),
                ("floor", models.CharField(blank=True, max_length=10)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["room_number"],
            },
        ),
    ]
