# Generated by Django 5.2.5 on 2025-09-23 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("code", models.CharField(max_length=20)),
                (
                    "default_duration",
                    models.PositiveIntegerField(
                        help_text="Default duration in minutes"
                    ),
                ),
                (
                    "buffer_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time after appointment in minutes"
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base cost for this appointment type",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("requires_preparation", models.BooleanField(default=False)),
                ("preparation_instructions", models.TextField(blank=True)),
                ("requires_fasting", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color_code",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for calendar display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_types",
                        to="accounts.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentWaitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preferred_date_start", models.DateField()),
                ("preferred_date_end", models.DateField()),
                ("preferred_time_start", models.TimeField(blank=True, null=True)),
                ("preferred_time_end", models.TimeField(blank=True, null=True)),
                (
                    "preferred_days",
                    models.JSONField(
                        default=list,
                        help_text="Preferred days of week (0=Monday, 6=Sunday)",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("notified", "Notified"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=1)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("response_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="appointments.appointmenttype",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="accounts.enhancedpatient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="accounts.enhancedstaffprofile",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_waitlist",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room_number", models.CharField(max_length=20, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation Room"),
                            ("examination", "Examination Room"),
                            ("procedure", "Procedure Room"),
                            ("surgery", "Surgery Room"),
                            ("lab", "Laboratory"),
                            ("imaging", "Imaging Room"),
                            ("therapy", "Therapy Room"),
                            ("conference", "Conference Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "features",
                    models.JSONField(
                        default=list, help_text="Room features and equipment"
                    ),
                ),
                ("floor", models.CharField(blank=True, max_length=10)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["room_number"],
                "indexes": [
                    models.Index(fields=["room_type"], name="rooms_room_ty_7b8350_idx"),
                    models.Index(
                        fields=["is_active", "is_available"],
                        name="rooms_is_acti_895516_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("equipment_id", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("maintenance", "Under Maintenance"),
                            ("out_of_order", "Out of Order"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_portable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="appointments.room",
                    ),
                ),
            ],
            options={
                "db_table": "equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Actual duration in minutes"),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(help_text="Reason for appointment")),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.JSONField(
                        blank=True,
                        help_text="Recurrence pattern (frequency, end date, etc.)",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("refunded", "Refunded"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.hospital",
                    ),
                ),
                (
                    "parent_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_appointments",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.enhancedpatient",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.enhancedstaffprofile",
                    ),
                ),
                (
                    "appointment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="appointments.appointmenttype",
                    ),
                ),
                (
                    "equipment_needed",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appointments",
                        to="appointments.equipment",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="appointments.room",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
            },
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(
                fields=["hospital"], name="appointment_hospita_e5869b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(fields=["code"], name="appointment_code_cfc35a_idx"),
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(
                fields=["is_active"], name="appointment_is_acti_2cf8c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmenttype",
            unique_together={("hospital", "code"), ("hospital", "name")},
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["provider", "status"], name="appointment_provide_535708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_6cd3b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["preferred_date_start", "preferred_date_end"],
                name="appointment_preferr_12724b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["priority", "created_at"], name="appointment_priorit_a32fde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_id"], name="equipment_equipme_c08382_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["category"], name="equipment_categor_7c0946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["status"], name="equipment_status_92035a_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["assigned_room"], name="equipment_assigne_eff9ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital"], name="appointment_hospita_e28458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "start_time"],
                name="appointment_appoint_e54e0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="appointment_patient_ee8848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["provider", "appointment_date"],
                name="appointment_provide_2c0628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital", "appointment_date"],
                name="appointment_hospita_5b3b23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_9fecd6_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["priority"], name="appointment_priorit_858412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["room", "appointment_date"],
                name="appointment_room_id_d566a2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("provider", "appointment_date", "start_time")},
        ),
    ]
