# Generated by Django 5.2.5 on 2025-09-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="parent_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_appointments",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="accounts.enhancedpatient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="accounts.enhancedstaffprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(fields=["code"], name="appointment_code_cfc35a_idx"),
        ),
        migrations.AddIndex(
            model_name="appointmenttype",
            index=models.Index(
                fields=["is_active"], name="appointment_is_acti_2cf8c8_idx"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="appointments.appointmenttype",
            ),
        ),
        migrations.AddField(
            model_name="appointmentwaitlist",
            name="appointment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="appointments.appointmenttype",
            ),
        ),
        migrations.AddField(
            model_name="appointmentwaitlist",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="accounts.enhancedpatient",
            ),
        ),
        migrations.AddField(
            model_name="appointmentwaitlist",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="accounts.enhancedstaffprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="equipment_needed",
            field=models.ManyToManyField(
                blank=True, related_name="appointments", to="appointments.equipment"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["room_type"], name="rooms_room_ty_7b8350_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active", "is_available"], name="rooms_is_acti_895516_idx"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="assigned_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="appointments.room",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="appointments.room",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["provider", "status"], name="appointment_provide_535708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_6cd3b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["preferred_date_start", "preferred_date_end"],
                name="appointment_preferr_12724b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentwaitlist",
            index=models.Index(
                fields=["priority", "created_at"], name="appointment_priorit_a32fde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_id"], name="equipment_equipme_c08382_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["category"], name="equipment_categor_7c0946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["status"], name="equipment_status_92035a_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["assigned_room"], name="equipment_assigne_eff9ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "start_time"],
                name="appointment_appoint_e54e0a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="appointment_patient_ee8848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["provider", "appointment_date"],
                name="appointment_provide_2c0628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_9fecd6_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["priority"], name="appointment_priorit_858412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["room", "appointment_date"],
                name="appointment_room_id_d566a2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("provider", "appointment_date", "start_time")},
        ),
    ]
