# Generated by Django 5.2.5 on 2026-01-01 14:51

import django.db.models.deletion
import django.utils.timezone
import encryption.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0005_emergencycontact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_key",
                    encryption.fields.EnhancedEncryptedCharField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "api_secret",
                    encryption.fields.EnhancedEncryptedCharField(max_length=255),
                ),
                (
                    "webhook_secret",
                    encryption.fields.EnhancedEncryptedCharField(
                        blank=True, max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        choices=[("v1", "Version 1"), ("v2", "Version 2")],
                        default="v1",
                        max_length=10,
                    ),
                ),
                (
                    "allowed_endpoints",
                    models.JSONField(
                        default=list, help_text="List of allowed API endpoints"
                    ),
                ),
                (
                    "data_retention_days",
                    models.IntegerField(
                        default=2555,
                        help_text="Data retention period in days (7 years)",
                    ),
                ),
                ("encryption_enabled", models.BooleanField(default=True)),
                (
                    "data_processing_agreement_signed",
                    models.BooleanField(default=False),
                ),
                ("privacy_notice_accepted", models.BooleanField(default=False)),
                ("consent_management_enabled", models.BooleanField(default=True)),
                ("audit_logging_enabled", models.BooleanField(default=True)),
                ("rate_limit_per_minute", models.IntegerField(default=100)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("rate_limit_per_day", models.IntegerField(default=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the integration"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_integration",
                        to="accounts.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital API Integration",
                "verbose_name_plural": "Hospital API Integrations",
                "db_table": "hospital_integrations",
            },
        ),
        migrations.CreateModel(
            name="DataProcessingConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("data_processing", "Data Processing Agreement"),
                            ("patient_data", "Patient Data Processing"),
                            ("appointment_reminders", "Appointment Reminders"),
                            ("emergency_contact", "Emergency Contact Processing"),
                            ("analytics", "Analytics and Reporting"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("consent_text", models.TextField()),
                ("consent_version", models.CharField(default="1.0", max_length=20)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="api_integration.hospitalintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Processing Consent",
                "verbose_name_plural": "Data Processing Consents",
                "db_table": "data_processing_consents",
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("status_code", models.IntegerField()),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "auth_status",
                    models.CharField(help_text="Authentication status", max_length=50),
                ),
                (
                    "data_subjects_affected",
                    models.IntegerField(
                        default=0, help_text="Number of data subjects affected"
                    ),
                ),
                ("personal_data_processed", models.BooleanField(default=False)),
                (
                    "data_categories",
                    models.JSONField(
                        default=list, help_text="Categories of data processed"
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("error_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_logs",
                        to="api_integration.hospitalintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Log",
                "verbose_name_plural": "API Logs",
                "db_table": "api_logs",
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("unauthorized_access", "Unauthorized Access"),
                            ("data_breach", "Data Breach"),
                            ("api_abuse", "API Abuse"),
                            ("authentication_failure", "Authentication Failure"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("affected_data_subjects", models.IntegerField(default=0)),
                ("data_categories_affected", models.JSONField(default=list)),
                ("investigation_notes", models.TextField(blank=True)),
                ("root_cause_analysis", models.TextField(blank=True)),
                ("remediation_actions", models.TextField(blank=True)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("reported_to_odpc_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_incidents",
                        to="api_integration.hospitalintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Incident",
                "verbose_name_plural": "Security Incidents",
                "db_table": "security_incidents",
            },
        ),
        migrations.AddIndex(
            model_name="hospitalintegration",
            index=models.Index(
                fields=["hospital", "status"], name="hospital_in_hospita_4fa50e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalintegration",
            index=models.Index(
                fields=["api_key"], name="hospital_in_api_key_5c7f0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalintegration",
            index=models.Index(
                fields=["created_at"], name="hospital_in_created_0b2225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataprocessingconsent",
            index=models.Index(
                fields=["integration", "consent_type"],
                name="data_proces_integra_937ede_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataprocessingconsent",
            index=models.Index(
                fields=["status", "created_at"], name="data_proces_status_26625a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataprocessingconsent",
            unique_together={("integration", "consent_type")},
        ),
        migrations.AddIndex(
            model_name="apilog",
            index=models.Index(
                fields=["integration", "created_at"], name="api_logs_integra_097b09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apilog",
            index=models.Index(
                fields=["endpoint", "status_code"], name="api_logs_endpoin_93eabc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apilog",
            index=models.Index(
                fields=["request_id"], name="api_logs_request_ea1a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apilog",
            index=models.Index(
                fields=["ip_address", "created_at"], name="api_logs_ip_addr_4db24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["integration", "status"], name="security_in_integra_a82f8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["severity", "created_at"], name="security_in_severit_5116f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityincident",
            index=models.Index(
                fields=["incident_type", "status"],
                name="security_in_inciden_a4746d_idx",
            ),
        ),
    ]
