# Generated by Django 5.2.5 on 2026-01-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalintegration",
            name="api_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
