# Generated by Django 5.2.5 on 2025-10-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_integrations", "0002_encrypt_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarintegration",
            name="sync_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
