# Generated by Django 5.2.5 on 2025-10-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("reminder", "Appointment Reminder"),
                    ("confirmation", "Appointment Confirmation"),
                    ("update", "Appointment Update"),
                    ("cancellation", "Appointment Cancellation"),
                    ("no_show", "No Show Notification"),
                    ("manual", "Manual Notification"),
                    ("notification", "Generic Notification"),
                ],
                max_length=20,
            ),
        ),
    ]
