# Generated by Django 5.2.5 on 2026-01-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_scheduledtask_task_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_68c9bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["delivery_method", "created_at"],
                name="notificatio_deliver_584f0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["patient_id", "status"], name="notificatio_patient_10aacf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["appointment_id", "status"],
                name="notificatio_appoint_8878cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["task", "status"], name="notificatio_task_id_0d4ecd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_4acc68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["task_type", "status"], name="notificatio_task_ty_fbf5a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["delivery_method", "created_at"],
                name="notificatio_deliver_5b8bda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["scheduled_time", "status"],
                name="notificatio_schedul_f95d4f_idx",
            ),
        ),
    ]
