# Generated by Django 4.2.7 on 2026-01-02 16:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog_notificatio_status_68c9bc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_task_id', models.UUIDField(unique=True)),
                ('task_type', models.CharField(max_length=20)),
                ('appointment_id', models.UUIDField()),
                ('patient_id', models.CharField(max_length=255)),
                ('provider_id', models.CharField(blank=True, max_length=255)),
                ('delivery_method', models.CharField(max_length=20)),
                ('failure_type', models.CharField(choices=[('max_retries_exceeded', 'Maximum Retries Exceeded'), ('permanent_failure', 'Permanent Failure'), ('invalid_recipient', 'Invalid Recipient'), ('service_unavailable', 'Service Unavailable'), ('authentication_error', 'Authentication Error'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('template_error', 'Template Error'), ('data_corruption', 'Data Corruption'), ('timeout', 'Timeout'), ('unknown', 'Unknown Error')], default='unknown', max_length=30)),
                ('final_error_message', models.TextField()),
                ('error_history', models.JSONField(default=list)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries_attempted', models.IntegerField(default=0)),
                ('original_message_data', models.JSONField(default=dict)),
                ('original_scheduled_time', models.DateTimeField()),
                ('final_failure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('manually_resolved', 'Manually Resolved'), ('archived', 'Archived'), ('auto_resolved', 'Auto Resolved'), ('requires_manual_intervention', 'Requires Manual Intervention')], default='pending_review', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolution_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_dead_letter_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['status', 'created_at'], name='notificati_status_fec4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['failure_type', 'created_at'], name='notificati_failure_4a3e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['delivery_method', 'status'], name='notificati_deliver_5c8e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['appointment_id', 'status'], name='notificati_appoint_8b9c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['patient_id', 'status'], name='notificati_patient_2a3c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['final_failure_time'], name='notificati_final_f_6a8b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletterqueue',
            index=models.Index(fields=['original_scheduled_time'], name='notificati_origina_7b8c9d_idx'),
        ),
    ]