# Generated by Django 5.2.5 on 2026-01-03 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_deadletterqueue"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_status_7eed86_idx",
            old_name="notificati_status_fec4b8_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_failure_1b29c9_idx",
            old_name="notificati_failure_4a3e2c_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_deliver_7bcd86_idx",
            old_name="notificati_deliver_5c8e7c_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_appoint_ca898e_idx",
            old_name="notificati_appoint_8b9c8f_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_patient_be1a80_idx",
            old_name="notificati_patient_2a3c4f_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_final_f_41481c_idx",
            old_name="notificati_final_f_6a8b9c_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="notificatio_origina_215632_idx",
            old_name="notificati_origina_7b8c9d_idx",
        ),
    ]
