"""
Django settings for mediremind_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-your-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS configuration for Render
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'a72e84e7df2d.ngrok-free.app']

# Add Render hostname if available
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    ALLOWED_HOSTS.append(os.environ['RENDER_EXTERNAL_HOSTNAME'])

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # Add token authentication
    'webpush',  # Re-enabled - pywebpush is compatible with Python 3.13
    'corsheaders',

    # Local apps
    'accounts',  # Centralized user management
    'authentication',  # Enhanced authentication system
    'appointments',
    'notifications',
    'medical_records',
    'billing',
    'prescriptions',
    'analytics',  # Analytics and dashboard system
    'calendar_integrations',  # Calendar integration system
    'patient_mobile_api',  # Patient mobile app API endpoints
    'api_integration',  # Hospital Management System API integration with KDPA compliance
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first for CORS to work properly
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.AuthenticationMiddleware',  # Custom optimized authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mediremind_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mediremind_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Use DATABASE_URL for Render deployment, fallback to individual env vars for local development
DATABASES = {
    'default': dj_database_url.config(
        default=f"postgresql://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', '')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'postgres')}?sslmode=require",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# Authentication settings
LOGIN_URL = '/auth/login/'
MAX_LOGIN_ATTEMPTS = 5
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400

# Always set CORS_ALLOW_ALL_ORIGINS to False for security
CORS_ALLOW_ALL_ORIGINS = False

# Build CORS_ALLOWED_ORIGINS list based on environment
CORS_ALLOWED_ORIGINS = []

if DEBUG:
    # Development settings - include local development URLs
    CORS_ALLOWED_ORIGINS.extend([
        "http://localhost:3000",
        "http://localhost:5173",
        "http://localhost:8080",
        "http://localhost:63320",  # Flutter app development server
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "http://127.0.0.1:8080",
        "http://127.0.0.1:63320",  # Flutter app development server
    ])
else:
    # Production settings - include production URLs
    CORS_ALLOWED_ORIGINS.extend([
        "https://mediremind-frontend.onrender.com",
        "https://mediremind-backend-cl6r.onrender.com",
    ])

# Add FRONTEND_URL from environment if available (works for both dev and prod)
if 'FRONTEND_URL' in os.environ:
    frontend_url = os.environ['FRONTEND_URL']
    if not frontend_url.startswith(('http://', 'https://')):
        # Use https for production, http for development
        scheme = 'https' if not DEBUG else 'http'
        frontend_url = f"{scheme}://{frontend_url}"
    if frontend_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(frontend_url)

# Add any additional origins from RENDER_EXTERNAL_HOSTNAME
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    render_url = f"https://{os.environ['RENDER_EXTERNAL_HOSTNAME']}"
    if render_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(render_url)

# Headers that are allowed during the actual request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Methods that are allowed during the actual request
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Security Headers for Production
# These settings enhance security by adding proper HTTP security headers
SECURE_SSL_REDIRECT = not DEBUG  # Redirect HTTP to HTTPS in production
SECURE_HSTS_SECONDS = 31536000  # 1 year - HTTP Strict Transport Security
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow site to be submitted to browser preload list
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filtering in browsers
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking attacks
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information

# Session and CSRF Cookie Security (consolidated settings)
# These are now handled in the main session/CSRF settings section below

# CSRF settings
# Helper function to ensure URLs have proper schemes
def ensure_url_scheme(url, default_scheme='https'):
    """Ensure URL has a proper scheme, add default if missing"""
    if not url:
        return url
    if not url.startswith(('http://', 'https://')):
        return f"{default_scheme}://{url}"
    return url

# Get environment variables and ensure they have proper schemes
frontend_url = ensure_url_scheme(os.getenv('FRONTEND_URL', 'http://localhost:3000'))
vite_dev_url = ensure_url_scheme(os.getenv('VITE_DEV_URL', 'http://localhost:5173'))
flutter_web_url = ensure_url_scheme(os.getenv('FLUTTER_WEB_URL', 'http://localhost:8080'))

CSRF_TRUSTED_ORIGINS = [
    frontend_url,
    vite_dev_url,
    flutter_web_url,
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8080",
    "https://mediremind-frontend.onrender.com",  # Production frontend URL
    "https://mediremind-backend-cl6r.onrender.com",  # Backend service URL from error
]

# Session settings for cross-origin requests
SESSION_COOKIE_SAMESITE = 'Lax'  # Standard setting for development
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookies
SESSION_COOKIE_AGE = 28800  # 8 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_DOMAIN = None  # Default domain setting

# CSRF settings for cross-origin
CSRF_COOKIE_SAMESITE = 'Lax'  # Standard setting for development
CSRF_COOKIE_SECURE = not DEBUG  # Use secure CSRF cookies in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for CSRF token

# Web Push settings
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv("VAPID_PUBLIC_KEY", ""),
    "VAPID_PRIVATE_KEY": os.getenv("VAPID_PRIVATE_KEY", ""),
    "VAPID_ADMIN_EMAIL": os.getenv("VAPID_ADMIN_EMAIL", "admin@mediremind.com")
}

# FCM settings
FCM_SERVER_KEY = os.getenv("FCM_SERVER_KEY", "")
FCM_PROJECT_ID = os.getenv("FCM_PROJECT_ID", "")
# Add v1 config toggles and credentials support
FCM_USE_V1 = os.getenv("FCM_USE_V1", "false")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")
FCM_PRIVATE_KEY_ID = os.getenv("FCM_PRIVATE_KEY_ID", "")
FCM_PRIVATE_KEY = os.getenv("FCM_PRIVATE_KEY", "")
FCM_CLIENT_EMAIL = os.getenv("FCM_CLIENT_EMAIL", "")
FCM_CLIENT_ID = os.getenv("FCM_CLIENT_ID", "")
FCM_TOKEN_URI = os.getenv("FCM_TOKEN_URI", "https://oauth2.googleapis.com/token")

# Validate VAPID settings
if not all([WEBPUSH_SETTINGS["VAPID_PUBLIC_KEY"], WEBPUSH_SETTINGS["VAPID_PRIVATE_KEY"]]):
    print("Warning: VAPID keys not properly configured. Web push notifications will not work.")
    print("Generate VAPID keys using: python notifications/generate_vapid_keys.py")

# Validate FCM settings
if not FCM_SERVER_KEY:
    print("Warning: FCM_SERVER_KEY not configured. Firebase push notifications will not work.")
    print("Get your FCM server key from Firebase Console -> Project Settings -> Cloud Messaging")

# Email settings
if DEBUG:
    # Development mode - print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("Development mode: Emails will be printed to console")
else:
    # Production mode - use transactional email service or SMTP
    EMAIL_SERVICE = os.getenv('EMAIL_SERVICE', 'smtp').lower()
    
    if EMAIL_SERVICE == 'sendgrid':
        # SendGrid configuration
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = 'smtp.sendgrid.net'
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
        EMAIL_HOST_USER = 'apikey'  # This is always 'apikey' for SendGrid
        EMAIL_HOST_PASSWORD = os.getenv('SENDGRID_API_KEY')
        EMAIL_TIMEOUT = 30
        
    elif EMAIL_SERVICE == 'mailgun':
        # Mailgun configuration
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = 'smtp.mailgun.org'
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
        EMAIL_HOST_USER = os.getenv('MAILGUN_SMTP_LOGIN')
        EMAIL_HOST_PASSWORD = os.getenv('MAILGUN_SMTP_PASSWORD')
        EMAIL_TIMEOUT = 30
        
    elif EMAIL_SERVICE == 'aws_ses':
        # AWS SES configuration
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = f'email-smtp.{os.getenv("AWS_REGION", "us-east-1")}.amazonaws.com'
        EMAIL_PORT = 587
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
        EMAIL_HOST_USER = os.getenv('AWS_SES_SMTP_USERNAME')
        EMAIL_HOST_PASSWORD = os.getenv('AWS_SES_SMTP_PASSWORD')
        EMAIL_TIMEOUT = 30
        
    else:
        # Fallback to Gmail SMTP (original configuration)
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
        EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
        EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
        EMAIL_TIMEOUT = 30  # Increased timeout
    
    # Warn if email settings are not configured
    if not EMAIL_HOST_PASSWORD:
        print(f"Warning: Email service '{EMAIL_SERVICE}' not properly configured. Email notifications will not work.")
        print("Required environment variables depend on EMAIL_SERVICE:")
        print("- sendgrid: SENDGRID_API_KEY")
        print("- mailgun: MAILGUN_SMTP_LOGIN, MAILGUN_SMTP_PASSWORD")
        print("- aws_ses: AWS_SES_SMTP_USERNAME, AWS_SES_SMTP_PASSWORD, AWS_REGION")
        print("- smtp (gmail): EMAIL_HOST_USER, EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@mediremind.com')

# Frontend URL setting for email templates
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# TextSMS Settings (Kenya SMS API)
TEXTSMS_API_KEY = os.getenv('TEXTSMS_API_KEY')
TEXTSMS_PARTNER_ID = os.getenv('TEXTSMS_PARTNER_ID', '14699')  # Your Partner ID
TEXTSMS_SENDER_ID = os.getenv('TEXTSMS_SENDER_ID', 'TextSMS')  # Your Shortcode/Sender ID

# Validate TextSMS settings
if not all([TEXTSMS_API_KEY, TEXTSMS_PARTNER_ID]):
    print("Warning: TextSMS settings not properly configured. SMS notifications will not work.")
    print("Required environment variables: TEXTSMS_API_KEY, TEXTSMS_PARTNER_ID")
    print("Get your API key from: https://sms.textsms.co.ke/ -> Partner Account -> API & Generate")

# Field-level encryption configuration
# SECURITY WARNING: Use a secure, randomly generated key in production
# This key should be stored securely and never committed to version control
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=')

# Enhanced encryption key management
ENCRYPTION_KEY_VERSION = os.getenv('ENCRYPTION_KEY_VERSION', 'v1')
ENCRYPTION_BACKUP_KEYS = {
    # Store backup keys for data encrypted with previous keys
    # Format: 'v0': 'old_encryption_key_here'
    'legacy': 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='  # Legacy key for existing encrypted data
}

# Force consistent encryption key across environments
# This ensures all deployments use the same key for encryption/decryption
FORCE_CONSISTENT_ENCRYPTION_KEY = True

# Patient Notification Settings
PATIENT_NOTIFICATION_SETTINGS = {
    # Email settings for patient communications
    'PATIENT_PORTAL_URL': os.getenv('PATIENT_PORTAL_URL', 'https://app.mediremind.com'),
    'SUPPORT_URL': os.getenv('SUPPORT_URL', 'https://mediremind.com/support'),
    'PRIVACY_URL': os.getenv('PRIVACY_URL', 'https://mediremind.com/privacy'),
    
    # Welcome email settings
    'SEND_WELCOME_EMAIL': os.getenv('SEND_WELCOME_EMAIL', 'True').lower() == 'true',
    'WELCOME_EMAIL_DELAY_SECONDS': int(os.getenv('WELCOME_EMAIL_DELAY_SECONDS', '5')),  # Delay before sending
    
    # Password settings
    'TEMPORARY_PASSWORD_LENGTH': int(os.getenv('TEMPORARY_PASSWORD_LENGTH', '12')),
    'PASSWORD_RESET_TOKEN_EXPIRY_HOURS': int(os.getenv('PASSWORD_RESET_TOKEN_EXPIRY_HOURS', '24')),
    
    # Email template settings
    'EMAIL_TEMPLATE_THEME': os.getenv('EMAIL_TEMPLATE_THEME', 'default'),
    'INCLUDE_HOSPITAL_BRANDING': os.getenv('INCLUDE_HOSPITAL_BRANDING', 'True').lower() == 'true',
    
    # Notification preferences
    'DEFAULT_EMAIL_NOTIFICATIONS': os.getenv('DEFAULT_EMAIL_NOTIFICATIONS', 'True').lower() == 'true',
    'ALLOW_NOTIFICATION_PREFERENCES': os.getenv('ALLOW_NOTIFICATION_PREFERENCES', 'True').lower() == 'true',
    
    # Security settings
    'REQUIRE_EMAIL_VERIFICATION': os.getenv('REQUIRE_EMAIL_VERIFICATION', 'False').lower() == 'true',
    'LOG_EMAIL_EVENTS': os.getenv('LOG_EMAIL_EVENTS', 'True').lower() == 'true',
}

# Convenience settings for backward compatibility
PATIENT_PORTAL_URL = PATIENT_NOTIFICATION_SETTINGS['PATIENT_PORTAL_URL']
SUPPORT_URL = PATIENT_NOTIFICATION_SETTINGS['SUPPORT_URL']
PRIVACY_URL = PATIENT_NOTIFICATION_SETTINGS['PRIVACY_URL']

# Ensure logs directory exists for logging
import os
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'logs/django.log',
            'formatter': 'verbose',
            'delay': True,  # Delay file creation until first log message
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'calendar_integrations': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Celery Beat schedule for periodic tasks
CELERY_BEAT_SCHEDULE = {
    'process-pending-reminders': {
        'task': 'notifications.tasks.process_pending_reminders',
        'schedule': crontab(minute='*/1'),  # every 1 minute
        'options': {'queue': 'notifications', 'expires': 55},
    },
    'cleanup-old-notification-logs': {
        'task': 'notifications.tasks.cleanup_old_notification_logs',
        'schedule': crontab(hour=3, minute=0),  # daily at 03:00 UTC
        'options': {'queue': 'notifications'},
    },
    'monitor-notification-health': {
        'task': 'notifications.tasks.monitor_notification_health',
        'schedule': crontab(minute='*/5'),  # every 5 minutes
        'options': {'queue': 'notifications', 'expires': 240},
    },
    'collect-queue-stats': {
        'task': 'notifications.tasks.collect_queue_stats',
        'schedule': crontab(minute='*/2'),  # every 2 minutes
        'options': {'queue': 'notifications', 'expires': 110},
    },
}

